#include "gui/categories/CategoriesWindow.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QTableWidget>
#include <QHeaderView>
#include <QLineEdit>
#include <QComboBox>
#include <QPushButton>
#include <QMessageBox>
using namespace finsight::core::models;
CategoriesWindow::CategoriesWindow(finsight::core::managers::FinanceTrackerBackend& backend,const std::string& userId,QWidget* parent):QWidget(parent),backend_(backend),userId_(userId){setupUi();refreshData();}
void CategoriesWindow::setUserId(const std::string& userId){userId_=userId;}
void CategoriesWindow::setupUi(){auto*l=new QVBoxLayout(this); table=new QTableWidget(); table->setColumnCount(4); table->setHorizontalHeaderLabels({"Name","Kind","Built-in","Id"}); table->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch); l->addWidget(table); auto*f=new QHBoxLayout(); nameEdit=new QLineEdit(); kindCombo=new QComboBox(); kindCombo->addItems({"Income","Expense","Savings","Investment"}); iconEdit=new QLineEdit(); addButton=new QPushButton("Add Custom"); deleteButton=new QPushButton("Delete Selected"); f->addWidget(nameEdit); f->addWidget(kindCombo); f->addWidget(iconEdit); f->addWidget(addButton); f->addWidget(deleteButton); l->addLayout(f); connect(addButton,&QPushButton::clicked,this,[this](){ if(userId_.empty()||nameEdit->text().trimmed().isEmpty()){QMessageBox::warning(this,"Invalid","User and name required.");return;} CategoryKind kind=CategoryKind::Expense; if(kindCombo->currentText()=="Income") kind=CategoryKind::Income; else if(kindCombo->currentText()=="Savings") kind=CategoryKind::Savings; else if(kindCombo->currentText()=="Investment") kind=CategoryKind::Investment; try{ backend_.transactions().createCategory(userId_,nameEdit->text().trimmed().toStdString(),kind,iconEdit->text().trimmed().toStdString(),false); refreshData(); emit dataChanged(); }catch(const std::exception& e){QMessageBox::warning(this,"Error",e.what());}}); connect(deleteButton,&QPushButton::clicked,this,[this](){ int r=table->currentRow(); if(r<0){return;} QString id=table->item(r,3)->text(); QString built=table->item(r,2)->text(); if(built=="Yes"){QMessageBox::information(this,"Blocked","Built-in categories cannot be deleted.");return;} try{ backend_.transactions().deleteCategory(userId_,id.toStdString()); refreshData(); emit dataChanged(); }catch(const std::exception& e){QMessageBox::warning(this,"Error",e.what());}});}
void CategoriesWindow::refreshData(){table->setRowCount(0); if(userId_.empty()) return; for(const auto& c: backend_.transactions().getCategoriesForUser(userId_)){ int r=table->rowCount(); table->insertRow(r); table->setItem(r,0,new QTableWidgetItem(QString::fromStdString(c.name))); QString k="Expense"; if(c.kind==CategoryKind::Income)k="Income"; else if(c.kind==CategoryKind::Savings)k="Savings"; else if(c.kind==CategoryKind::Investment)k="Investment"; table->setItem(r,1,new QTableWidgetItem(k)); table->setItem(r,2,new QTableWidgetItem(c.builtIn?"Yes":"No")); table->setItem(r,3,new QTableWidgetItem(QString::fromStdString(c.id))); }}
