#include "ReportService.h"

#include "BudgetService.h"
#include "TransactionService.h"

#include <algorithm>
#include <iomanip>
#include <ios>
#include <map>
#include <optional>
#include <sstream>
#include <stdexcept>

using namespace std;

namespace finsight::core::services {

namespace {

std::string money(double value) {
    std::ostringstream stream;
    stream << std::fixed << std::setprecision(2) << value;
    return stream.str();
}

std::string transactionTypeText(models::TransactionType type) {
    return type == models::TransactionType::Income ? "Income" : "Expense";
}

std::string periodText(const models::Date& from, const models::Date& to) {
    return from.toString() + " to " + to.toString();
}

}  // namespace

// Generates a report by filtering transactions and summarizing the results.
models::FinancialReport ReportService::generateReport(const models::ReportRequest& request,
                                                      const TransactionService& transactionService,
                                                      const BudgetService& budgetService) const {
    if (request.userId.empty()) {
        throw std::invalid_argument("Report requires a user.");
    }
    if (request.to < request.from) {
        throw std::invalid_argument("Report end date cannot be before start date.");
    }

    models::TransactionFilter filter;
    filter.from = request.from;
    filter.to = request.to;

    models::FinancialReport report {.request = request};
    report.transactions = transactionService.filterTransactions(request.userId, filter);

    std::map<std::string, models::CategoryReportLine> categoryTotals;
    for (const auto& transaction : report.transactions) {
        if (transaction.type == models::TransactionType::Income) {
            report.totalIncome += transaction.amount;
        } else {
            report.totalExpenses += transaction.amount;
            const auto& category = transactionService.requireCategory(transaction.categoryId);
            auto& line = categoryTotals[category.id];
            line.categoryId = category.id;
            line.categoryName = category.name;
            line.amount += transaction.amount;
        }
    }
    report.net = report.totalIncome - report.totalExpenses;

    for (const auto& [_, line] : categoryTotals) {
        report.categoryExpenses.push_back(line);
    }
    std::sort(report.categoryExpenses.begin(),
              report.categoryExpenses.end(),
              [](const auto& left, const auto& right) {
                  return left.amount > right.amount;
              });

    models::YearMonth currentPeriod {request.from.year, request.from.month};
    report.impactedBudgets = budgetService.summarizeBudgets(request.userId, currentPeriod, transactionService);

    const double savingsRate = report.totalIncome <= 0.0 ? 0.0 : report.net / report.totalIncome * 100.0;
    const auto topCategory = report.categoryExpenses.empty() ? std::optional<models::CategoryReportLine> {}
                                                             : std::optional<models::CategoryReportLine> {report.categoryExpenses.front()};

    std::ostringstream text;
    text << "FinSight Financial Report\n";
    text << "=========================\n\n";
    text << "Report period: " << periodText(request.from, request.to) << "\n";
    text << "Generated by: FinSight\n\n";

    text << "Executive Summary\n";
    text << "-----------------\n";
    text << "During this period, total income was EGP " << money(report.totalIncome)
         << " and total expenses were EGP " << money(report.totalExpenses) << ". ";
    if (report.net >= 0.0) {
        text << "The period ended with a positive net balance of EGP " << money(report.net) << ".\n";
    } else {
        text << "The period ended with a deficit of EGP " << money(-report.net) << ".\n";
    }
    text << "Savings rate: " << money(savingsRate) << "%.\n";
    if (topCategory) {
        text << "Largest expense category: " << topCategory->categoryName
             << " at EGP " << money(topCategory->amount) << ".\n";
    } else {
        text << "No expense categories were recorded in this period.\n";
    }
    text << "Transaction count: " << report.transactions.size() << ".\n\n";

    text << "Key Totals\n";
    text << "----------\n";
    text << std::left << std::setw(22) << "Total income" << "EGP " << money(report.totalIncome) << "\n";
    text << std::left << std::setw(22) << "Total expenses" << "EGP " << money(report.totalExpenses) << "\n";
    text << std::left << std::setw(22) << "Net balance" << "EGP " << money(report.net) << "\n";
    text << std::left << std::setw(22) << "Savings rate" << money(savingsRate) << "%\n\n";

    // Key Totals uses std::left; reset before zero-padded month values (otherwise month 3 prints as "30").
    text << std::resetiosflags(std::ios_base::adjustfield) << std::setfill(' ');

    text << "Category Breakdown\n";
    text << "------------------\n";
    if (report.categoryExpenses.empty()) {
        text << "No expenses were recorded by category.\n";
    } else {
        for (const auto& line : report.categoryExpenses) {
            const double share = report.totalExpenses <= 0.0 ? 0.0 : line.amount / report.totalExpenses * 100.0;
            text << "- " << line.categoryName << ": EGP " << money(line.amount)
                 << " (" << money(share) << "% of expenses)\n";
        }
    }
    text << "\nBudget Review\n";
    text << "-------------\n";
    if (report.impactedBudgets.empty()) {
        text << "No budgets are configured for " << currentPeriod.year << '-'
             << std::right << std::setw(2) << std::setfill('0') << currentPeriod.month << "\n";
        text << std::setfill(' ') << std::left;
    } else {
        for (const auto& status : report.impactedBudgets) {
            const auto& category = transactionService.requireCategory(status.budget.categoryId);
            const double used = status.budget.limit <= 0.0 ? 0.0 : status.spent / status.budget.limit * 100.0;
            text << "- " << category.name
                 << ": limit EGP " << money(status.budget.limit)
                 << ", spent EGP " << money(status.spent)
                 << ", remaining EGP " << money(status.remaining)
                 << ", used " << money(used) << "%"
                 << (status.overspent ? " - OVERSPENT" : "")
                 << "\n";
        }
    }
    text << "\nTransaction Detail\n";
    text << "------------------\n";
    if (report.transactions.empty()) {
        text << "No transactions matched this report period.\n";
    } else {
        for (const auto& transaction : report.transactions) {
            const auto& category = transactionService.requireCategory(transaction.categoryId);
            text << "- " << transaction.date.toString()
                 << " | " << transactionTypeText(transaction.type)
                 << " | " << category.name
                 << " | " << transaction.title
                 << " | EGP " << money(transaction.amount);
            if (!transaction.merchant.empty()) {
                text << " | " << transaction.merchant;
            }
            text << "\n";
        }
    }

    report.exportedText = text.str();

    return report;
}

}  // namespace finsight::core::services
